#! /bin/bash

function download_easeagent() {
    curl -Lk https://github.com/megaease/release/releases/download/easeagent/easeagent.jar -o entrypoint/easeagent.jar
}

function build_docker_images() {
    mvn clean install -am -Dmaven.test.skip=true -PbuildDocker -pl spring-petclinic-config-server,spring-petclinic-discovery-server,spring-petclinic-visits-service,spring-petclinic-customers-service,spring-petclinic-api-gateway

}

download_easeagent && \
build_docker_images && \
docker-compose up -d && \
echo "Done."
